// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Document = {};

var ClassList = {};

var Style = {};

var $$Element = {
  Style: Style
};

var $$Window = {};

export {
  $$Document ,
  ClassList ,
  $$Element ,
  $$Window ,
}
/* No side effect */
