// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Docson from "docson";
import Docson$1 from "docson";
import * as Js_promise from "rescript/lib/es6/js_promise.js";

function Docson$2(Props) {
  var tag = Props.tag;
  var element = React.useRef(null);
  React.useEffect((function () {
          var segment = "https://raw.githubusercontent.com/rescript-lang/rescript-compiler/" + tag + "/docs/docson/build-schema.json";
          var __x = fetch(segment);
          var __x$1 = Js_promise.then_((function (prim) {
                  return prim.json();
                }), __x);
          Js_promise.then_((function (schema) {
                  var _el = element.current;
                  if (!(_el == null)) {
                    Docson$1.templateBaseUrl = "/static/docson";
                    Docson.default.doc("docson-root", schema, undefined, segment);
                  }
                  return Promise.resolve(undefined);
                }), __x$1);
        }), []);
  return React.createElement("div", {
              ref: element,
              id: "docson-root"
            });
}

var make = Docson$2;

export {
  make ,
}
/* react Not a pure module */
