// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Meta from "./components/Meta.mjs";
import * as Next from "./bindings/Next.mjs";
import * as React from "react";
import * as Navigation from "./components/Navigation.mjs";
import * as Playground from "./Playground.mjs";

function Try$default(Props) {
  var overlayState = React.useState(function () {
        return false;
      });
  return React.createElement(React.Fragment, undefined, React.createElement(Meta.make, {
                  description: "Try ReScript in the browser",
                  title: "ReScript Playground"
                }), React.createElement(Next.Head.make, {
                  children: React.createElement("style", undefined, "body { background-color: #010427; } ")
                }), React.createElement("div", {
                  className: "text-16"
                }, React.createElement("div", {
                      className: "text-gray-40 text-14"
                    }, React.createElement(Navigation.make, {
                          fixed: false,
                          overlayState: overlayState
                        }), React.createElement(Playground.make, {}))));
}

var $$default = Try$default;

export {
  $$default ,
  $$default as default,
}
/* Meta Not a pure module */
