// Generated by ReScript, PLEASE EDIT WITH CARE


var allManualVersions = [
  [
    "latest",
    "v9.1 - v10.0"
  ],
  [
    "v9.0.0",
    "v8.2 - v9.0"
  ],
  [
    "v8.0.0",
    "v6.0 - v8.2"
  ]
];

var allReactVersions = [
  [
    "latest",
    "v0.11.0"
  ],
  [
    "v0.10.0",
    "v0.10.0"
  ]
];

function languageManual(version) {
  return [[
            "Overview",
            "/docs"
          ]];
}

var tools = [[
    "Syntax Lookup",
    "/syntax-lookup"
  ]];

export {
  allManualVersions ,
  allReactVersions ,
  languageManual ,
  tools ,
}
/* No side effect */
