// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Markdown from "../components/Markdown.mjs";
import * as DocsLayout from "./DocsLayout.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var tocData = (require('index_data/manual_latest_toc.json'));

var LatestLayout = DocsLayout.Make({
      tocData: tocData
    });

function ManualDocsLayout$Latest(Props) {
  var frontmatter = Props.frontmatter;
  var componentsOpt = Props.components;
  var children = Props.children;
  var components = componentsOpt !== undefined ? Caml_option.valFromOption(componentsOpt) : Markdown.$$default;
  var tmp = {
    title: "rescript-fp-core",
    metaTitleCategory: "Docs",
    components: components,
    theme: "Reason",
    children: children
  };
  if (frontmatter !== undefined) {
    tmp.frontmatter = Caml_option.valFromOption(frontmatter);
  }
  return React.createElement(LatestLayout.make, tmp);
}

var Latest = {
  make: ManualDocsLayout$Latest
};

export {
  LatestLayout ,
  Latest ,
}
/* LatestLayout Not a pure module */
